_wandb:
    value:
        cli_version: 0.24.0
        e:
            693wsmxv57ysb9wx512irvohkbhswv2c:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "11811160064"
                codePath: scripts/export_to_wandb.py
                codePathLocal: scripts/export_to_wandb.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "211812872192"
                email: kubapelka12@gmail.com
                executable: /Library/Developer/CommandLineTools/usr/bin/python3
                git:
                    commit: ac49ae74707542f9c36d468a00407d142af7fa52
                    remote: https://github.com/kubi-4327/rekwizytor.git
                host: Kubas-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/kubapelka/rekwizytor/scripts/export_to_wandb.py
                python: CPython 3.9.6
                root: /Users/kubapelka/rekwizytor
                startedAt: "2026-01-21T20:35:10.561362Z"
                writerId: 693wsmxv57ysb9wx512irvohkbhswv2c
        m: []
        python_version: 3.9.6
        t:
            "3":
                - 2
                - 13
                - 14
                - 15
                - 16
                - 62
            "4": 3.9.6
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
difficulty_mode:
    value: medium
embedding_model:
    value: Unknown Embedding Model
embedding_model_code:
    value: unknown
enrichment_model:
    value: No Enrichment
enrichment_model_code:
    value: none
mvs_weight_context:
    value: 0.3
mvs_weight_identity:
    value: 0.4
mvs_weight_physical:
    value: 0.3
target_query_count:
    value: 200
tester_model:
    value: gpt-4o-mini
tester_model_code:
    value: gpt-4o-mini
use_dynamic_weights:
    value: false
