version: '3.8'

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: rekwizytor-pocketbase-test
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase_data:/pb_data
      - ./pocketbase_public:/pb_public
    environment:
      - POCKETBASE_ADMIN_EMAIL=admin@test.local
      - POCKETBASE_ADMIN_PASSWORD=admin123456
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8090/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  default:
    name: rekwizytor-test-network
