_wandb:
    value:
        cli_version: 0.24.0
        m: []
        python_version: 3.9.6
        t:
            "3":
                - 13
                - 14
                - 15
                - 16
            "4": 3.9.6
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
difficulty_mode:
    value: medium
embedding_model:
    value: Unknown Embedding Model
embedding_model_code:
    value: unknown
enrichment_model:
    value: No Enrichment
enrichment_model_code:
    value: none
mvs_weight_context:
    value: 0.3
mvs_weight_identity:
    value: 0.4
mvs_weight_physical:
    value: 0.3
target_query_count:
    value: 200
tester_model:
    value: gpt-4o-mini
tester_model_code:
    value: gpt-4o-mini
use_dynamic_weights:
    value: false
